### ISSUE TITLE
Exception function

### ISSUE THREAD

**Issue by mrakrmakmrka** [Wexop/OptimalScrapsOrganization#1]
The mod is nice, but it would be nice if you could add the ability to include items in the exclusion list so that they are not affected when sorting. 

Also, it would be great if sorting would synchronize the new loot position for all players, not just the host.

**Comment by Wexop** [comment]
Hello,

Yeah this is a good idea, will add that soon 🙂

The mod should already sync position for every players (right now all players needs the mod to sync, it can change in the futur)

**Comment by Wexop** [comment]
Done in 1.0.2 !
